# 使用 Node.js 22 作为基础镜像
FROM node:22-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY . .

RUN pnpm install --ignore-scripts

EXPOSE 9090

# 启动命令
CMD ["sh", "-c", "pnpm prisma generate && pnpm prisma migrate deploy && pnpm test && pnpm start"]